<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Append' => '追加',
    'Application' => 'アプリケーション',
    'Are you sure to delete this item?' => 'この項目を削除します。よろしいですか?',
    'Assigned' => '割当て済み',
    'Assignment' => '権限の割当て',
    'Assignments' => '権限の割当て',
    'Avaliable' => '割当て可能',
    'Class Name' => 'クラス名',
    'Create' => '作成',
    'Create Menu' => 'メニューを作成',
    'Create Permission' => '許可を作成',
    'Create Role' => 'ロールを作成',
    'Create Route' => 'ルートを作成',
    'Create Rule' => '規則を作成',
    'Create route' => 'ルートを作成',
    'Data' => 'データ',
    'Delete' => '削除',
    'Description' => '説明',
    'Generate Routes' => 'ルートを生成',
    'Help' => 'ヘルプ',
    'ID' => 'ID',
    'Menus' => 'メニュー',
    'Name' => '名前',
    'Order' => '順序',
    'Parent' => '親',
    'Parent Name' => '親の名前',
    'Permission' => '許可',
    'Permissions' => '許可',
    'Reset' => 'リセット',
    'Roles' => 'ロール',
    'Route' => 'ルート',
    'Routes' => 'ルート',
    'Rule Name' => '規則の名前',
    'Rules' => '規則',
    'Search' => '検索',
    'Type' => 'タイプ',
    'Update' => '更新',
    'Update Menu' => 'メニューを更新',
    'Update Permission' => '許可を更新',
    'Update Role' => 'ロールを更新',
    'Update Rule' => '規則を更新',
    'User' => 'ユーザ',
    'Username' => 'ユーザ名',
    'Users' => 'ユーザ',
];
