<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 * @author dinhtrung.
 */
return [
    'Append' => 'Thêm vào',
    'Application' => 'Ứng dụng',
    'Are you sure to delete this item?' => 'Bạn có chắc chắn xóa mục này?',
    'Assigned' => 'Giao',
    'Assignments' => 'Cấp quyền',
    'Avaliable' => 'Có sẵn',
    'Class Name' => 'Tên lớp',
    'Create' => 'Tạo mới',
    'Create Menu' => 'tạo menu',
    'Create Permission' => 'Tạo Quyền',
    'Create Role' => 'Tạo Vai trò',
    'Create Route' => 'Tạo Route',
    'Create Rule' => 'Tạo Quy tắc',
    'Create route' => 'Tạo Route',
    'Data' => 'Dữ liệu',
    'Delete' => 'Xóa bỏ',
    'Description' => 'Mô tả',
    'Generate Routes' => 'Tạo Route',
    'Help' => 'Trợ giúp',
    'ID' => 'ID',
    'Menus' => 'Trình đơn',
    'Name' => 'Tên',
    'Order' => 'Thứ tự',
    'Parent' => 'Cha mẹ',
    'Parent Name' => 'Tên cha',
    'Permission' => 'Quyền',
    'Permissions' => 'Quyền',
    'Reset' => 'Thiết lập lại',
    'Roles' => 'Vai trò',
    'Route' => 'Route',
    'Routes' => 'Các Route',
    'Rule Name' => 'Tên Quy tắc',
    'Rules' => 'Quy tắc',
    'Search' => 'Tìm kiếm',
    'Type' => 'Kiểu',
    'Update' => 'Sửa',
    'Update Menu' => 'Sửa Menu',
    'Update Permission' => 'Sửa Quyền',
    'Update Role' => 'Sửa Vai trò',
    'Update Rule' => 'Sửa Quy tắc',
    'Username' => 'Tên đăng nhập',
];
